### ISSUE TITLE
Add Include Slot To Import SubTree From File

### ISSUE THREAD

**Issue by furesoft** [polterguy/magic.lambda#7]

**Comment by polterguy** [comment]
Hi Furesoft, you can actually already kind of do this by using something resembling the following;

```
io.file.load:/foo/bar.hl
add:x:@your-destination-here
   hyper2lambda:x:@io.file.load
```

This allows you to _"concatenate"_ files any ways you see fit, constructing larger tree structures, from several smaller. We're doing this all the time in fact to create _"function objects from smaller entities"_ ...

**Comment by furesoft** [comment]
Yeah, but I want to add the nodes to the root node

**Comment by polterguy** [comment]
That's might be a problem. I'd suggest creating an **[.exe]** node where your execute lambda is, and add into this ...
